name: 'Query Extension Version'
description: "Query an Azure DevOps extension's version"

inputs:
  token:
    description: 'Azure DevOps token'
    required: true
  publisher-id:
    description: 'Publisher ID of the extension'
    required: true
  extension-id:
    description: 'Extension ID of the extension'
    required: true

outputs:
  version:
    description: 'Version of the extension'
    value: ${{ steps.query-extension-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 'Query extension version'
      id: 'query-extension-version'
      shell: pwsh
      run: ./script.ps1 `
        -Token ${{ inputs.token }} `
        -PublisherId ${{ inputs.publisher-id }} `
        -ExtensionId ${{ inputs.extension-id }}
