name: Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: PSScriptAnalyzer
        uses: devblackops/github-action-psscriptanalyzer@854038567344559afaaa8ccb7a014452b99d86ee # tag=v2.4.0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
